### ISSUE TITLE
Canceling all units in carrier's queue crashes the game

### ISSUE THREAD

**Issue by KYSXD** [BoomerangAide/GPTP-For-VS2008#26] opened 2017-09-22 18:44 UTC
Removing all units in a carrier's queue crashes.

This doesn't happen with Reaver.

**Comment by BoomerangAide** [comment] 2017-10-06 15:16
Commenting out **jmpPatch(secondaryOrd_TrainFighterWrapper,	0x00466790, 2);** in hooks\orders\unit_making\unit_train_inject.cpp seems to fix it, so I guess the issue is in the secondaryOrd_TrainFighter function.I'm looking into it.

**Comment by BoomerangAide** [comment] 2017-10-08 15:32
Fixed in Version 4.020

**Closed as completed by BoomerangAide** 2017-10-08 15:32 UTC
